sudo: required

services:
  - docker

before_install:
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name generate asciidoctor/docker-asciidoctor src/asciidoctor.sh

after_error:
  - docker logs generate

after_failure:
  - docker logs generate

after_success:
  - cd /tmp; echo "${DEPLOY_PRIVATE_KEY}" > id_rsa_deploy; chmod 600 id_rsa_deploy; eval "$(ssh-agent -s)"; ssh-add id_rsa_deploy;
  - cd /tmp; git clone --depth 2 --branch gh-pages "${GH_REF}" gh-pages
  - cd /tmp/gh-pages;mkdir -p "${TRAVIS_BRANCH}";cd "${TRAVIS_BRANCH}"; cp -R $TRAVIS_BUILD_DIR/dist/* .
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push "${GH_REF}" gh-pages:gh-pages
